### ISSUE TITLE
Dashboard and Briefing

### ISSUE THREAD

**Issue by BennerLukas** [BennerLukas/takeawaste#4]

**Comment by Madhour** [comment]
- [ ] Vendor Dashboard with monthly, weekly, daily forecast
- [ ] Presented to each vendor, based on their sales (accounts for sales outside of app)

**Comment by BennerLukas** [comment]
Define a input schema needed for the dashboard and hand over to issue #5

**Comment by BennerLukas** [comment]
2 datasets:

raw_data
predicted_data -> given by #3
